[package]
name = "client"
version = "0.1.0"
rust-version = "1.56"
edition = "2021"

[dependencies]
anchor-client = "0.26.0"
anchor-lang = "0.26.0"
raydium-amm-v3 = {path = "../programs/amm", features = ["no-entrypoint"]}
solana-sdk = "1.13.5"
solana-client = "1.13.5"
solana-account-decoder = "1.13.5"
spl-token = { version = "3.5.0", features=["no-entrypoint"] }
spl-associated-token-account = "1.0.3"
mpl-token-metadata = { version = "1.2.7", features = ["no-entrypoint"] }
clap = { version = "3.0.0-rc.0", features = ["derive"] }
shellexpand = "2.1.0"
anyhow = "1.0.32"
rand = "0.7.3"
hex = "0.4.3"
configparser = "3.0.0"
borsh = "0.9.0"
serde_json = { version = "1.0.78" }
serde = { version = "1.0", features = ["derive"] }
arrayref = "0.3.6"
bs58 = { version = "0.4.0"}
bincode = { version = "1.3.3" }